worker_processes auto;
pid /tmp/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout;
  error_log /dev/stderr warn;
  client_body_temp_path /tmp/client_body 1 2;
  proxy_temp_path /tmp/proxy_temp 1 2;
  fastcgi_temp_path /tmp/fastcgi_temp 1 2;
  scgi_temp_path /tmp/scgi_temp 1 2;
  uwsgi_temp_path /tmp/uwsgi_temp 1 2;
  client_max_body_size 9m;
  client_body_buffer_size 128k;
  client_body_timeout 30s;
  sendfile on;
  server_tokens off;

  server {
    listen 3000;

    location / {
      proxy_pass http://web:3000;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
